version: "3.9"

services:
  db:
    container_name: postgresql
    image: postgres:latest
    restart: always
    volumes:
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - ${DB_PORT}:5432

  redis:
    image: redis:6.2-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

  main:
    depends_on:
      - db
      - redis
    container_name: mainService
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./.env



volumes:
  postgresdb-data:
    driver: local
  redis-data:
    driver: local
