server:
  host: "0.0.0.0"
  port: "8080"
postgres:
  db_host: "localhost"
  db_port: "5432"
  db_user: "banner_user"
  db_password: "banner_pass"
  db_name: "banner"
redis:
  redis_host:  "localhost"
  redis_port: "6379"
  redis_user: ""
  redis_password: "redis_password"